language: node_js
node_js:
  - "stable"
services:
  - docker
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: sh $TRAVIS_BUILD_DIR/deploy.sh
  on:
    branch: master
