language: node_js
node_js:
  - "11.10.0"
services:
  - docker
before_script:
  - npm install
  - npm install -g node-sass
script:
  - CI=false npm run test
  - CI=false npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: sh $TRAVIS_BUILD_DIR/deploy.sh
  on:
    branch: master
