language: node_js
node_js:
  - "stable"
services:
  - docker
before_script:
  - npm install
  - npm install -g node-sass
script:
  - npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: sh $TRAVIS_BUILD_DIR/deploy.sh
  on:
    branch: master
